name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.4' # Set the Go version

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...
